# Article-length prose for the length test (written for this red team; neutral content).
P = [
"Lighthouses were once the most important buildings on any dangerous coast. Before radio and satellite navigation, a ship approaching land at night had little more than a chart, a compass and the hope of a light on the horizon. Each lighthouse flashed in its own pattern, so a navigator who counted the seconds between flashes could tell which tower he was looking at, and therefore where he was.",
"The earliest lights were simple fires burning in iron baskets on top of stone towers. They consumed enormous amounts of coal or wood, and on a wet and windy night they could barely be seen a few miles out to sea. Keepers spent the whole night feeding the flames, and a single careless hour could cost a ship and every life on board.",
"Everything changed in the eighteen twenties, when the French engineer Augustin Fresnel designed a new kind of lens. Instead of one heavy curved piece of glass, he arranged dozens of thin rings of prisms around a single lamp. The rings bent the light into a narrow, brilliant beam that could be seen more than twenty miles away, while burning only a fraction of the fuel.",
"Life in a lighthouse was lonely and demanding. Keepers trimmed the wicks, polished the brass and cleaned the glass every single day. They wound the clockwork that turned the lens, logged the weather, and in a storm they might not sleep at all. Many towers stood on bare rocks miles from shore, and supplies arrived only when the sea was calm enough for a boat to land.",
"Some keepers became famous for their courage. Grace Darling, the daughter of a keeper in the north of England, rowed out with her father through a violent storm in eighteen thirty eight to rescue the survivors of a wrecked steamer. Newspapers across the country told the story, and for a while she was one of the best known young women in Britain.",
"During the twentieth century, electricity and automatic equipment slowly replaced the keepers. A lamp that switched itself on at dusk and a motor that turned the lens needed no one to watch over them. One by one the towers were automated, and the last keepers left their posts, often with mixed feelings about the end of a way of life that had lasted for centuries.",
"Today most ships find their way with satellite positioning, and many people assume that lighthouses are no longer needed. Yet the lights still shine. Electronic systems can fail, and a sailor whose screens have gone dark is still very glad to see a familiar flash on the horizon. Many towers have also become museums, where visitors climb the narrow stairs and look out across the water.",
"Standing at the top of an old lighthouse, it is easy to imagine the keepers who once lived there. The wind still rattles the windows, the sea still breaks against the rocks below, and at dusk the great lens still begins to turn, sending its beam out into the darkness exactly as it has done for more than a hundred years.",
]
LONG2 = " ".join(P[:4])   # ~2.2 min
LONG5 = " ".join(P)       # ~4.5 min
