#!/usr/bin/env node
// Turns bench/results.json into assets/diagrams/performance.mmd: a beautiful-mermaid 1.1.3 `xychart-beta`
// bar chart of the warm real-time factor by text length. Never edit performance.mmd by hand; re-run
// `node bench/run.mjs ...` and then this script.
//
//   node bench/chart.mjs [--in bench/results.json] [--out assets/diagrams/performance.mmd] [--check] [--allow-contended]
//
// A results.json whose `clean` is false (the machine was busy) is refused unless --allow-contended is given,
// and a contended chart says so in its title.
//
// Syntax constraints of beautiful-mermaid 1.1.3 (docs/research/2026-09-upgrade/R08 §1.5, and
// src/xychart/parser.ts): category labels are split on commas and must be unquoted (quotes render
// literally, a comma starts a new category); series cannot be named, so the chart is single-series; the
// title and axis titles cannot contain a double quote. The repo's diagram renderer also expands `@token`
// palette names, so the output must not contain "@". The diagram type is detected from the FIRST line of the
// raw text (before %% comments are stripped), so `xychart-beta` must come first and the comments after it.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
const opt = (name, fallback) => { const i = argv.indexOf(`--${name}`); return i === -1 ? fallback : argv[i + 1]; };
const IN = resolve(opt('in', join(HERE, 'results.json')));
const OUT = resolve(opt('out', join(HERE, '../assets/diagrams/performance.mmd')));
const CHECK = argv.includes('--check');

const r = JSON.parse(readFileSync(IN, 'utf8'));
if (!r.clean && !argv.includes('--allow-contended')) {
  console.error(`${IN} was measured on a busy machine (clean: false); re-run bench/run.mjs when it is idle, or pass --allow-contended`);
  process.exit(1);
}
const LABEL = { sentence: 'Sentence', paragraph: 'Paragraph', page: 'Page', 'long article': 'Long article' };
const fmtInt = (n) => n.toLocaleString('en-US').replace(/,/g, ' '); // no commas: they split categories

const cats = r.warm.map((w) => `${LABEL[w.label] ?? w.label} (${fmtInt(w.words)} words)`);
const vals = r.warm.map((w) => Number(w.rtf.median.toFixed(1)));
const top = Math.ceil((Math.max(...vals) * 1.12) / 5) * 5;
const chip = r.machine.chip.replace(/^Apple /, '');
const title = `Kokoro-82M on ${chip}: seconds of speech per second of work${r.clean ? '' : ' (busy machine)'}`;

const xTitle = `Text length · warm median of ${r.conditions.runs_per_text} runs · voice ${r.conditions.voice} at ${r.conditions.speed}x`;

for (const s of [title, xTitle, ...cats]) {
  if (/["\]\[,@]/.test(s)) throw new Error(`label would break the chart syntax: ${s}`);
}

const mmd = `xychart-beta
    %% GENERATED by bench/chart.mjs from bench/results.json (${r.generated_at.slice(0, 10)}). Do not edit by hand.
    %% Warm median of ${r.conditions.runs_per_text} runs per text, voice ${r.conditions.voice}, speed ${r.conditions.speed}x, helper ${r.software.helper_version} (${r.software.helper_git_sha.slice(0, 7)}), mlx-audio ${r.software.mlx_audio}.
    %% Real-time factor = audio seconds (WAV header) / wall seconds. Time to first audio equals the full synthesis time (no streaming).
    title "${title}"
    x-axis "${xTitle}" [${cats.join(', ')}]
    y-axis "Times faster than real time" 0 --> ${top}
    bar [${vals.join(', ')}]
`;

if (CHECK) {
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== mmd) { console.error(`STALE: ${OUT} does not match ${IN}`); process.exit(1); }
  console.log(`${OUT} is up to date`);
} else {
  writeFileSync(OUT, mmd);
  console.log(`wrote ${OUT}\n${mmd}`);
}
