/**
 * Background Service Worker (Phase 2.4/2.5/2.6)
 *
 * Manages context menu, coordinates between components,
 * and handles offscreen document for audio playback.
 */

import type {
  SpeakInOffscreenMessage,
  StopInOffscreenMessage,
  OffscreenSpeakResponse,
  OffscreenMessage,
} from '../shared/types';
import { loadSettings } from '../shared/settings-defaults';
import { readSelection, resolveContextMenuText } from '../shared/selection';

/**
 * Constants
 */
const CONTEXT_MENU_ID = 'natural-tts-speak-selection';
const OFFSCREEN_DOCUMENT_PATH = 'offscreen/offscreen.html';
const OFFSCREEN_JUSTIFICATION =
  'Plays speech generated by the local helper via object URLs, independent of the popup';

/**
 * Offscreen lifecycle state. `creatingOffscreen` makes creation single-flight
 * (two speak requests at once must not both call createDocument, the second
 * would throw). `closingOffscreen` lets a new request wait for an idle close
 * to finish instead of racing it. `speaksInFlight` stops an idle signal from
 * closing the document under a request the service worker is about to send.
 */
let creatingOffscreen: Promise<void> | null = null;
let closingOffscreen: Promise<void> | null = null;
let speaksInFlight = 0;
const SPEAK_COMMAND = 'speak-selection';
const STOP_COMMAND = 'stop-speaking';

/**
 * Initialize background service worker
 */
console.log('[Natural TTS] Background service worker loaded');

/**
 * Set up context menu on extension install
 *
 * NOTE: an extension-side prewarmHelper() that POSTed /speak with a whitespace
 * text was removed in v1.4.1 — on lazy-load helpers (pre-rebuild) it stripped
 * to empty after normalize_text() and hung the Python worker, breaking every
 * subsequent /speak. Helper-side eager-load (tts_worker.py) is the proper
 * warmup mechanism; extension-side prewarm was redundant.
 */
chrome.runtime.onInstalled.addListener(async () => {
  console.log('[Background] Extension installed/updated');
  await setupContextMenu();
});

chrome.runtime.onStartup.addListener(async () => {
  console.log('[Background] Extension started');
  await setupContextMenu();
});

/**
 * Create context menu item for text selection
 */
async function setupContextMenu(): Promise<void> {
  try {
    // Remove existing menu items
    await chrome.contextMenus.removeAll();

    // Create new menu item
    chrome.contextMenus.create({
      id: CONTEXT_MENU_ID,
      title: 'Speak selected text',
      contexts: ['selection'],
    });

    console.log('[Background] Context menu created');
  } catch (error) {
    console.error('[Background] Error setting up context menu:', error);
  }
}

/**
 * Handle context menu clicks
 */
chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  console.log('[Background] Context menu clicked:', {
    menuItemId: info.menuItemId,
    tabId: tab?.id,
    hasSelectionText: !!info.selectionText,
  });

  // Only handle our menu item
  if (info.menuItemId !== CONTEXT_MENU_ID) {
    return;
  }

  try {
    // Read the selection on demand (activeTab was granted by this click),
    // falling back to info.selectionText for PDFs, iframes and inputs.
    const selectedText = await resolveContextMenuText(info, tab);

    if (!selectedText) {
      console.warn('[Background] No selected text to speak');
      return;
    }

    await speakText(selectedText);
  } catch (error) {
    console.error('[Background] Error handling context menu click:', error);
  }
});

/**
 * Keyboard commands (manifest "commands"; no default keys, bound by the user
 * at chrome://extensions/shortcuts). A shortcut grants activeTab on the
 * current tab, so speak-selection can read the selection there. It cannot
 * reach the PDF viewer or cross-origin iframes; the context menu is the path
 * for those.
 */
chrome.commands.onCommand.addListener(async (command, tab) => {
  try {
    if (command === STOP_COMMAND) {
      await stopSpeaking();
      return;
    }

    if (command === SPEAK_COMMAND) {
      if (tab?.id === undefined || tab.id < 0) {
        console.warn('[Background] speak-selection: no tab to read from');
        return;
      }
      const selectedText = (await readSelection(tab.id)).trim();
      if (!selectedText) {
        console.warn('[Background] speak-selection: nothing selected (or the page cannot be scripted)');
        return;
      }
      await speakText(selectedText);
    }
  } catch (error) {
    console.error(`[Background] Error handling command ${command}:`, error);
  }
});

/**
 * Speak text through the offscreen document with the user's preferences.
 * Resolves when playback completes, fails, or is stopped.
 */
async function speakText(text: string): Promise<void> {
  speaksInFlight++;
  try {
    // Get user preferences
    const { voice, speed } = await getPreferences();

    // Ensure offscreen document exists
    await ensureOffscreenDocument();

    // Send text to offscreen document for speech generation
    const response = await sendToOffscreen({
      type: 'SPEAK_IN_OFFSCREEN',
      text,
      voice,
      speed,
    });

    if (response.type === 'SPEAK_STOPPED') {
      console.log('[Background] Speech stopped');
    } else if (response.success) {
      console.log('[Background] Speech playback completed successfully');
    } else {
      console.error('[Background] Speech playback failed:', response.error);
    }
  } finally {
    speaksInFlight--;
  }
}

/**
 * The offscreen document reports that it has been idle; close it. Ignored
 * while this worker is still sending it a speak request.
 */
chrome.runtime.onMessage.addListener((message: OffscreenMessage): boolean => {
  if (message?.type === 'OFFSCREEN_IDLE') {
    void closeIdleOffscreenDocument();
  }
  return false;
});

async function closeIdleOffscreenDocument(): Promise<void> {
  if (speaksInFlight > 0 || creatingOffscreen || closingOffscreen) {
    return;
  }
  closingOffscreen = (async () => {
    try {
      await chrome.offscreen.closeDocument();
    } catch (error) {
      console.warn('[Background] closeDocument failed:', error);
    }
  })();
  try {
    await closingOffscreen;
  } finally {
    closingOffscreen = null;
  }
}

/**
 * Stop speech everywhere: the offscreen document stops and settles its
 * pending speak request, and an open popup stops its own playback. Having
 * no receiver (nothing ever spoke) is not an error.
 */
async function stopSpeaking(): Promise<void> {
  const message: StopInOffscreenMessage = { type: 'STOP_IN_OFFSCREEN' };
  try {
    await chrome.runtime.sendMessage(message);
  } catch (error) {
    console.warn('[Background] Stop: no receiver', error);
  }
}

/**
 * Get user preferences from storage
 * Uses centralized settings from Phase 2.6
 */
async function getPreferences(): Promise<{ voice: string; speed: number; autoPlay: boolean }> {
  try {
    const settings = await loadSettings();
    return {
      voice: settings.selectedVoice,
      speed: settings.selectedSpeed,
      autoPlay: settings.autoPlay,
    };
  } catch (error) {
    console.error('[Background] Error loading preferences:', error);
    // Return defaults from loadSettings fallback
    const settings = await loadSettings();
    return {
      voice: settings.selectedVoice,
      speed: settings.selectedSpeed,
      autoPlay: settings.autoPlay,
    };
  }
}

/**
 * Ensure offscreen document exists
 * Creates it if it doesn't exist, or returns if already exists
 */
async function ensureOffscreenDocument(): Promise<void> {
  // An idle close in progress must finish before we look, or we would find
  // the document, return, and then message a document that is going away.
  if (closingOffscreen) {
    await closingOffscreen;
  }

  // Another request is already creating it: wait for that one.
  if (creatingOffscreen) {
    await creatingOffscreen;
    return;
  }

  creatingOffscreen = createOffscreenDocumentIfMissing();
  try {
    await creatingOffscreen;
  } finally {
    creatingOffscreen = null;
  }
}

async function createOffscreenDocumentIfMissing(): Promise<void> {
  try {
    const existingContexts = await chrome.runtime.getContexts({
      contextTypes: ['OFFSCREEN_DOCUMENT' as chrome.runtime.ContextType],
      documentUrls: [chrome.runtime.getURL(OFFSCREEN_DOCUMENT_PATH)],
    });

    if (existingContexts.length > 0) {
      return;
    }

    // AUDIO_PLAYBACK alone lets Chrome close the document 30 s after creation
    // if nothing has played yet, which kills a long /speak mid-fetch. BLOBS is
    // truthful (playback goes through object URLs) and keeps it alive; the
    // document then closes itself via OFFSCREEN_IDLE.
    await chrome.offscreen.createDocument({
      url: OFFSCREEN_DOCUMENT_PATH,
      reasons: ['AUDIO_PLAYBACK', 'BLOBS'] as chrome.offscreen.Reason[],
      justification: OFFSCREEN_JUSTIFICATION,
    });

    // createDocument resolves when the URL has been navigated to, but
    // offscreen.js's onMessage listener registers AFTER its module finishes
    // loading. Without this wait, the first sendMessage races the script
    // load and gets dropped silently. 300ms is conservative; the script is
    // ~6KB and parses in well under that on real hardware.
    await new Promise(r => setTimeout(r, 300));
  } catch (error) {
    // sendToOffscreen still runs and reports the failure; keep the cause.
    console.warn('[Background] Could not create the offscreen document:', error);
  }
}

/**
 * Send message to offscreen document, retrying once on connection failure
 * (defends against the offscreen-listener registration race).
 */
async function sendToOffscreen(
  message: SpeakInOffscreenMessage
): Promise<OffscreenSpeakResponse> {
  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      const response = await chrome.runtime.sendMessage(message) as OffscreenSpeakResponse | undefined;
      if (response) return response;
      // No response — the listener wasn't ready. Retry after a short delay.
      console.warn(`[Background] sendMessage returned no response (attempt ${attempt})`);
    } catch (error) {
      console.warn(`[Background] sendMessage threw (attempt ${attempt}):`, error);
    }
    if (attempt === 1) {
      await new Promise(r => setTimeout(r, 500));
    }
  }
  return {
    type: 'SPEAK_ERROR',
    success: false,
    error: 'Offscreen document unreachable after retry — check service worker console',
  };
}

/**
 * Export for testing
 */
if (typeof globalThis !== 'undefined') {
  (globalThis as any).__serviceWorkerTestHelpers = {
    setupContextMenu,
    getPreferences,
    ensureOffscreenDocument,
    sendToOffscreen,
    speakText,
    stopSpeaking,
  };
}
