/**
 * Background Service Worker (Phase 2.4/2.5/2.6)
 *
 * Manages context menu, coordinates between components,
 * and handles offscreen document for audio playback.
 */

import type {
  SpeakInOffscreenMessage,
  StopInOffscreenMessage,
  OffscreenSpeakResponse,
  OffscreenMessage,
  SystemVoiceStatusResponse,
} from '../shared/types';
import { loadSettings, pinPreviousDefaultVoice } from '../shared/settings-defaults';
import type { HelperUnavailableAction } from '../shared/system-voice';
import { SYSTEM_VOICE_FAILED_MESSAGE } from '../shared/system-voice';
import {
  speakWithSystemVoice,
  stopSystemVoice,
  isSystemVoiceSpeaking,
  type SystemVoiceFinished,
} from './system-voice-engine';
import { readSelection, resolveContextMenuText } from '../shared/selection';
import { showErrorBadge, clearErrorBadge, showSystemVoiceHint } from '../shared/error-badge';
import { userMessageForError } from '../shared/helper-errors';
import { getStoredPort, saveHelperPort } from '../shared/config';

const NOTHING_SELECTED_MENU = 'Could not read the selected text. Select it again and retry.';
const NOTHING_SELECTED_SHORTCUT =
  'Nothing to speak. Select text first; shortcuts cannot read PDFs, frames from other sites or browser pages, so right-click there.';

/**
 * Constants
 */
const CONTEXT_MENU_ID = 'natural-tts-speak-selection';
const OFFSCREEN_DOCUMENT_PATH = 'offscreen/offscreen.html';
const OFFSCREEN_JUSTIFICATION =
  'Plays speech generated by the local helper via object URLs, independent of the popup';

/**
 * Offscreen lifecycle state. `creatingOffscreen` makes creation single-flight
 * (two speak requests at once must not both call createDocument, the second
 * would throw). `closingOffscreen` lets a new request wait for an idle close
 * to finish instead of racing it. `speaksInFlight` stops an idle signal from
 * closing the document under a request the service worker is about to send.
 */
let creatingOffscreen: Promise<void> | null = null;
let closingOffscreen: Promise<void> | null = null;
let speaksInFlight = 0;
/**
 * Bumped by every stop. A speak request records it when the user asked to
 * speak and gives up if it changed before the request reached the offscreen
 * document: a stop pressed while the selection is read, the document is
 * created, or the send is retried has no job there to stop yet.
 */
let stopGeneration = 0;
const SPEAK_COMMAND = 'speak-selection';
const STOP_COMMAND = 'stop-speaking';

/**
 * Initialize background service worker
 */
console.log('[Natural TTS] Background service worker loaded');

/**
 * Set up context menu on extension install
 *
 * NOTE: an extension-side prewarmHelper() that POSTed /speak with a whitespace
 * text was removed in v1.4.1 — on lazy-load helpers (pre-rebuild) it stripped
 * to empty after normalize_text() and hung the Python worker, breaking every
 * subsequent /speak. Helper-side eager-load (tts_worker.py) is the proper
 * warmup mechanism; extension-side prewarm was redundant.
 */
chrome.runtime.onInstalled.addListener(async (details?: chrome.runtime.InstalledDetails) => {
  console.log('[Background] Extension installed/updated');
  await setupContextMenu();
  // OD-5's af_heart default is for new installs: an update keeps the voice it used.
  if (await pinPreviousDefaultVoice(details)) {
    console.log('[Background] Kept the previous default voice (af_bella) for this update');
  }
});

chrome.runtime.onStartup.addListener(async () => {
  console.log('[Background] Extension started');
  await setupContextMenu();
});

/**
 * Create context menu item for text selection
 */
async function setupContextMenu(): Promise<void> {
  try {
    // Remove existing menu items
    await chrome.contextMenus.removeAll();

    // Create new menu item
    chrome.contextMenus.create({
      id: CONTEXT_MENU_ID,
      title: 'Speak selected text',
      contexts: ['selection'],
    });

    console.log('[Background] Context menu created');
  } catch (error) {
    console.error('[Background] Error setting up context menu:', error);
  }
}

/**
 * Handle context menu clicks
 */
chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  console.log('[Background] Context menu clicked:', {
    menuItemId: info.menuItemId,
    tabId: tab?.id,
    hasSelectionText: !!info.selectionText,
  });

  // Only handle our menu item
  if (info.menuItemId !== CONTEXT_MENU_ID) {
    return;
  }
  const generation = stopGeneration;

  try {
    // Read the selection on demand (activeTab was granted by this click),
    // falling back to info.selectionText for PDFs, iframes and inputs.
    const selectedText = await resolveContextMenuText(info, tab);

    if (!selectedText) {
      console.warn('[Background] No selected text to speak');
      await showErrorBadge(NOTHING_SELECTED_MENU);
      return;
    }

    await speakText(selectedText, generation);
  } catch (error) {
    console.error('[Background] Error handling context menu click:', error);
    await showErrorBadge(userMessageForError(error));
  }
});

/**
 * Keyboard commands (manifest "commands"; no default keys, bound by the user
 * at chrome://extensions/shortcuts). A shortcut grants activeTab on the
 * current tab, so speak-selection can read the selection there. It cannot
 * reach the PDF viewer or cross-origin iframes; the context menu is the path
 * for those.
 */
chrome.commands.onCommand.addListener(async (command, tab) => {
  try {
    if (command === STOP_COMMAND) {
      await stopSpeaking();
      return;
    }

    if (command === SPEAK_COMMAND) {
      const generation = stopGeneration;
      if (tab?.id === undefined || tab.id < 0) {
        console.warn('[Background] speak-selection: no tab to read from');
        await showErrorBadge(NOTHING_SELECTED_SHORTCUT);
        return;
      }
      const selectedText = (await readSelection(tab.id)).trim();
      if (!selectedText) {
        console.warn('[Background] speak-selection: nothing selected (or the page cannot be scripted)');
        await showErrorBadge(NOTHING_SELECTED_SHORTCUT);
        return;
      }
      await speakText(selectedText, generation);
    }
  } catch (error) {
    console.error(`[Background] Error handling command ${command}:`, error);
    await showErrorBadge(userMessageForError(error));
  }
});

/**
 * Speak text through the offscreen document with the user's preferences.
 * Resolves once playback has started, or when the request failed or was
 * stopped before that. A failure shows the error badge; a start (or a
 * deliberate stop) clears it. How a started playback ends arrives later as
 * SPEAK_FINISHED (onMessage below): this worker never holds a message open
 * for the length of the audio, which Chrome cuts off after ~5 minutes.
 *
 * When the helper cannot be reached, the same text is spoken with the system
 * voice (OD-2) unless the user chose "Show an error"; the icon then shows the
 * neutral install hint, or the error badge if the system voice fails too.
 */
async function speakText(text: string, generation: number = stopGeneration): Promise<void> {
  speaksInFlight++;
  try {
    const stopped = () => stopGeneration !== generation;

    // A new request replaces whatever the system voice is saying.
    stopSystemVoice();

    // Get user preferences, and the helper port the offscreen document
    // cannot read from chrome.storage itself
    const [{ voice, speed, whenHelperUnavailable }, port] = await Promise.all([
      getPreferences(),
      getStoredPort(),
    ]);

    // Ensure offscreen document exists
    if (!stopped()) await ensureOffscreenDocument();

    // Send text to offscreen document for speech generation
    let response = stopped()
      ? STOPPED_BEFORE_SEND
      : await sendToOffscreen({ type: 'SPEAK_IN_OFFSCREEN', text, voice, speed, ...(port ? { port } : {}) }, stopped);

    // The offscreen document found the helper on another port: remember it.
    if (response.success && response.port && response.port !== port) {
      await saveHelperPort(response.port).catch(error => {
        console.warn('[Background] Could not save the helper port:', error);
      });
    }

    if (
      !response.success &&
      response.helperUnavailable === true &&
      whenHelperUnavailable === 'system-voice' &&
      !stopped()
    ) {
      console.log('[Background] Helper unavailable: speaking with the system voice');
      const fallback = await speakWithSystemVoice(text, voice, speed, {
        isStopped: stopped,
        onFinished: reportSystemVoiceFinished,
      });
      response = fallback.success ? fallback : { ...fallback, error: SYSTEM_VOICE_FAILED_MESSAGE };
    }

    if (response.type === 'SPEAK_STOPPED') {
      console.log('[Background] Speech stopped');
    } else if (response.type === 'SPEAK_STARTED') {
      console.log('[Background] Speech playback started');
    } else if (response.success) {
      console.log('[Background] Speech playback completed successfully');
    } else {
      console.error('[Background] Speech playback failed:', response.error);
    }

    if (response.success) {
      await (response.engine === 'system' ? showSystemVoiceHint() : clearErrorBadge());
    } else {
      await showErrorBadge(response.error || 'Speech failed. Try again.');
    }
  } finally {
    speaksInFlight--;
  }
}

/** How a started system-voice speech ended: the install hint stays, a failure shows the error badge. */
function reportSystemVoiceFinished(outcome: SystemVoiceFinished): void {
  void (outcome.success
    ? showSystemVoiceHint()
    : showErrorBadge(outcome.error || 'Speech failed. Try again.'));
}

/**
 * Messages from the offscreen document and the popup. The offscreen document
 * reports that it has been idle (close it; ignored while this worker is still
 * sending it a speak request) and how a started playback ended. The popup
 * asks for system-voice speech after finding the helper unreachable, asks
 * whether the system voice is speaking, and stops speech with its Stop button.
 */
chrome.runtime.onMessage.addListener((
  message: OffscreenMessage,
  _sender?: chrome.runtime.MessageSender,
  sendResponse?: (response: OffscreenSpeakResponse | SystemVoiceStatusResponse) => void
): boolean => {
  if (message?.type === 'SPEAK_WITH_SYSTEM_VOICE') {
    const generation = stopGeneration;
    void speakWithSystemVoice(message.text, message.voice, message.speed, {
      isStopped: () => stopGeneration !== generation,
      onFinished: reportSystemVoiceFinished,
    }).then(response => {
      // The popup shows its own errors; a working system voice shows the install hint.
      if (response.success) void showSystemVoiceHint();
      sendResponse?.(response);
    });
    return true;
  }
  if (message?.type === 'SYSTEM_VOICE_STATUS_QUERY') {
    sendResponse?.({ type: 'SYSTEM_VOICE_STATUS', speaking: isSystemVoiceSpeaking() });
    return false;
  }
  if (message?.type === 'STOP_IN_OFFSCREEN') {
    // The popup's Stop (this worker's own stop broadcast never reaches it):
    // cancel a request still on its way and silence the system voice. The
    // offscreen document answers the message; this listener does not.
    stopGeneration++;
    stopSystemVoice();
    return false;
  }
  if (message?.type === 'OFFSCREEN_IDLE') {
    void closeIdleOffscreenDocument();
  } else if (message?.type === 'SPEAK_FINISHED') {
    // A started playback ended: to the end or stopped (clear the badge), or
    // failed mid-way (show it).
    void (message.success
      ? clearErrorBadge()
      : showErrorBadge(message.error || 'Speech failed. Try again.'));
  }
  return false;
});

async function closeIdleOffscreenDocument(): Promise<void> {
  if (speaksInFlight > 0 || creatingOffscreen || closingOffscreen) {
    return;
  }
  closingOffscreen = (async () => {
    try {
      await chrome.offscreen.closeDocument();
    } catch (error) {
      console.warn('[Background] closeDocument failed:', error);
    }
  })();
  try {
    await closingOffscreen;
  } finally {
    closingOffscreen = null;
  }
}

/**
 * Stop speech everywhere: the system voice stops, the offscreen document
 * stops and settles its pending speak request, and an open popup stops its
 * own playback. Having
 * no receiver (nothing ever spoke) is not an error.
 */
async function stopSpeaking(): Promise<void> {
  stopGeneration++;
  stopSystemVoice();
  const message: StopInOffscreenMessage = { type: 'STOP_IN_OFFSCREEN' };
  try {
    await chrome.runtime.sendMessage(message);
  } catch (error) {
    console.warn('[Background] Stop: no receiver', error);
  }
}

/**
 * Get user preferences from storage
 * Uses centralized settings from Phase 2.6
 */
async function getPreferences(): Promise<{
  voice: string;
  speed: number;
  whenHelperUnavailable: HelperUnavailableAction;
}> {
  // loadSettings never rejects: it falls back to the defaults itself.
  const settings = await loadSettings();
  return {
    voice: settings.selectedVoice,
    speed: settings.selectedSpeed,
    whenHelperUnavailable: settings.whenHelperUnavailable,
  };
}

/**
 * Ensure offscreen document exists
 * Creates it if it doesn't exist, or returns if already exists
 */
async function ensureOffscreenDocument(): Promise<void> {
  // An idle close in progress must finish before we look, or we would find
  // the document, return, and then message a document that is going away.
  if (closingOffscreen) {
    await closingOffscreen;
  }

  // Another request is already creating it: wait for that one.
  if (creatingOffscreen) {
    await creatingOffscreen;
    return;
  }

  creatingOffscreen = createOffscreenDocumentIfMissing();
  try {
    await creatingOffscreen;
  } finally {
    creatingOffscreen = null;
  }
}

async function createOffscreenDocumentIfMissing(): Promise<void> {
  try {
    const existingContexts = await chrome.runtime.getContexts({
      contextTypes: ['OFFSCREEN_DOCUMENT' as chrome.runtime.ContextType],
      documentUrls: [chrome.runtime.getURL(OFFSCREEN_DOCUMENT_PATH)],
    });

    if (existingContexts.length > 0) {
      return;
    }

    // AUDIO_PLAYBACK alone lets Chrome close the document 30 s after creation
    // if nothing has played yet, which kills a long /speak mid-fetch. BLOBS is
    // truthful (playback goes through object URLs) and keeps it alive; the
    // document then closes itself via OFFSCREEN_IDLE.
    await chrome.offscreen.createDocument({
      url: OFFSCREEN_DOCUMENT_PATH,
      reasons: ['AUDIO_PLAYBACK', 'BLOBS'] as chrome.offscreen.Reason[],
      justification: OFFSCREEN_JUSTIFICATION,
    });

    // createDocument resolves when the URL has been navigated to, but
    // offscreen.js's onMessage listener registers AFTER its module finishes
    // loading. Without this wait, the first sendMessage races the script
    // load and gets dropped silently. 300ms is conservative; the script is
    // ~6KB and parses in well under that on real hardware.
    await new Promise(r => setTimeout(r, 300));
  } catch (error) {
    // sendToOffscreen still runs and reports the failure; keep the cause.
    console.warn('[Background] Could not create the offscreen document:', error);
  }
}

/**
 * Send message to offscreen document, retrying once on connection failure
 * (defends against the offscreen-listener registration race).
 */
const STOPPED_BEFORE_SEND: OffscreenSpeakResponse = { type: 'SPEAK_STOPPED', success: true };

async function sendToOffscreen(
  message: SpeakInOffscreenMessage,
  stopped: () => boolean
): Promise<OffscreenSpeakResponse> {
  for (let attempt = 1; attempt <= 2; attempt++) {
    if (stopped()) return STOPPED_BEFORE_SEND;
    try {
      const response = await chrome.runtime.sendMessage(message) as OffscreenSpeakResponse | undefined;
      if (response) return response;
      // No response — the listener wasn't ready. Retry after a short delay.
      console.warn(`[Background] sendMessage returned no response (attempt ${attempt})`);
    } catch (error) {
      console.warn(`[Background] sendMessage threw (attempt ${attempt}):`, error);
    }
    if (attempt === 1) {
      await new Promise(r => setTimeout(r, 500));
    }
  }
  return {
    type: 'SPEAK_ERROR',
    success: false,
    error: 'Could not start audio playback. Try again.',
  };
}
